apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  containers:
    - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: server--env
        - name: GCLOUD_STORAGE_BUCKET
          valueFrom:
            configMapKeyRef:
              key: GCLOUD_STORAGE_BUCKET
              name: server--env
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_CLOUD_PROJECT
              name: server--env
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              key: INSTANCE_CONNECTION_NAME
              name: server--env
        - name: PUBSUB_TOPIC_PALINDROME
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_TOPIC_PALINDROME
              name: server--env
        - name: PUBSUB_TOPIC_SORT
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_TOPIC_SORT
              name: server--env
        - name: SQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: SQL_DATABASE
              name: server--env
        - name: SQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SQL_PASSWORD
              name: server--env
        - name: SQL_USER
          valueFrom:
            configMapKeyRef:
              key: SQL_USER
              name: server--env
      image: backend
      name: backend
      ports:
        - containerPort: 8081
      resources: {}
  restartPolicy: OnFailure
status: {}
