---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "saas-1-config-jan8"
  namespace: "sorting-as-a-service"
  labels:
    app: "saas-1"
data:
  GCLOUD_STORAGE_BUCKET: "object-storage"
  SQL_DATABASE: "sorting-as-a-service-db"
  SQL_USER: "root"
  SQL_PASSWORD: "dbinstance123"
  INSTANCE_CONNECTION_NAME: "sorting-as-a-service:europe-west1:sorting-as-a-service-dbinstance2"
  PUBSUB_TOPIC_SORT: "sorting"
  PUBSUB_TOPIC_PALINDROME: "palindrome"
  DB_HOST: "127.0.0.1"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "saas-1"
  namespace: "sorting-as-a-service"
  labels:
    app: "saas-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "saas-1"
  template:
    metadata:
      labels:
        app: "saas-1"
    spec:
      containers:
      - name: "saas-frontend-sha256-1"
        image: "europe-west1-docker.pkg.dev/sorting-as-a-service/sorting-as-a-service-repo/saas-frontend@sha256:6550e4f3bd6ee4cceb0540f1907569202216bb948500120e702583f326ba5049"
        env:
        - name: "GCLOUD_STORAGE_BUCKET"
          valueFrom:
            configMapKeyRef:
              key: "GCLOUD_STORAGE_BUCKET"
              name: "saas-1-config-jan8"
        - name: "SQL_DATABASE"
          valueFrom:
            configMapKeyRef:
              key: "SQL_DATABASE"
              name: "saas-1-config-jan8"
        - name: "SQL_USER"
          valueFrom:
            configMapKeyRef:
              key: "SQL_USER"
              name: "saas-1-config-jan8"
        - name: "SQL_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "SQL_PASSWORD"
              name: "saas-1-config-jan8"
        - name: "INSTANCE_CONNECTION_NAME"
          valueFrom:
            configMapKeyRef:
              key: "INSTANCE_CONNECTION_NAME"
              name: "saas-1-config-jan8"
        - name: "PUBSUB_TOPIC_SORT"
          valueFrom:
            configMapKeyRef:
              key: "PUBSUB_TOPIC_SORT"
              name: "saas-1-config-jan8"
        - name: "PUBSUB_TOPIC_PALINDROME"
          valueFrom:
            configMapKeyRef:
              key: "PUBSUB_TOPIC_PALINDROME"
              name: "saas-1-config-jan8"
        - name: "DB_HOST"
          valueFrom:
            configMapKeyRef:
              key: "DB_HOST"
              name: "saas-1-config-jan8"
      - name: "gce-proxy-2"
        image: "gcr.io/cloudsql-docker/gce-proxy:1.28.0"
        command:
        - "/cloud_sql_proxy -instances=sorting-as-a-service:europe-west1:sorting-as-a-service-dbinstance2=tcp:3306"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "saas-1-hpa-um3x"
  namespace: "sorting-as-a-service"
  labels:
    app: "saas-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "saas-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
