apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-22T11:08:02Z"
  generation: 1
  labels:
    app: saas-app-1
    tier: backend
  name: saas-app-1
  namespace: sorting-as-a-service
  resourceVersion: "47883"
  uid: 2a935272-b9fa-49bf-b312-eaf39fec4b40
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: saas-app-1
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saas-app-1
        tier: backend
    spec:
      containers:
      - env:
        - name: GCLOUD_STORAGE_BUCKET
          valueFrom:
            configMapKeyRef:
              key: GCLOUD_STORAGE_BUCKET
              name: saas-app-1-config-jyvi
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: saas-app-1-config-jyvi
        - name: SQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: SQL_DATABASE
              name: saas-app-1-config-jyvi
        - name: SQL_USER
          valueFrom:
            configMapKeyRef:
              key: SQL_USER
              name: saas-app-1-config-jyvi
        - name: SQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SQL_PASSWORD
              name: saas-app-1-config-jyvi
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              key: INSTANCE_CONNECTION_NAME
              name: saas-app-1-config-jyvi
        - name: PUBSUB_TOPIC_SORT
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_TOPIC_SORT
              name: saas-app-1-config-jyvi
        - name: PUBSUB_TOPIC_PALINDROME
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_TOPIC_PALINDROME
              name: saas-app-1-config-jyvi
        image: europe-west1-docker.pkg.dev/sorting-as-a-service/sorting-as-a-service-repo/saas-backend@sha256:5b8bc6390f396e3ebd7666e26eaddc62d17fdb7f4eae510cfa64d9d51d5258f3
        imagePullPolicy: IfNotPresent
        name: saas-backend-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: kubernetes-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"