---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "saas-app-1-config-gqcm"
  namespace: "sorting-as-a-service"
  labels:
    app: "saas-app-1"
    tier: "backend"
data:
  GCLOUD_STORAGE_BUCKET: "object-storage"
  DB_HOST: "35.187.56.77"
  SQL_DATABASE: "sorting-as-a-service-db"
  SQL_USER: "root"
  SQL_PASSWORD: "dbinstance123"
  INSTANCE_CONNECTION_NAME: "sorting-as-a-service:europe-west1:sorting-as-a-service-dbinstance2"
  PUBSUB_TOPIC_SORT: "sorting"
  PUBSUB_TOPIC_PALINDROME: "palindrome"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "saas-app-1"
  namespace: "sorting-as-a-service"
  labels:
    app: "saas-app-1"
    tier: "backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "saas-app-1"
      tier: "backend"
  template:
    metadata:
      labels:
        app: "saas-app-1"
        tier: "backend"
    spec:
      containers:
      - name: "saas-backend-sha256-1"
        image: "europe-west1-docker.pkg.dev/sorting-as-a-service/sorting-as-a-service-repo/saas-backend@sha256:5b8bc6390f396e3ebd7666e26eaddc62d17fdb7f4eae510cfa64d9d51d5258f3"
        env:
        - name: "GCLOUD_STORAGE_BUCKET"
          valueFrom:
            configMapKeyRef:
              key: "GCLOUD_STORAGE_BUCKET"
              name: "saas-app-1-config-gqcm"
        - name: "DB_HOST"
          valueFrom:
            configMapKeyRef:
              key: "DB_HOST"
              name: "saas-app-1-config-gqcm"
        - name: "SQL_DATABASE"
          valueFrom:
            configMapKeyRef:
              key: "SQL_DATABASE"
              name: "saas-app-1-config-gqcm"
        - name: "SQL_USER"
          valueFrom:
            configMapKeyRef:
              key: "SQL_USER"
              name: "saas-app-1-config-gqcm"
        - name: "SQL_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "SQL_PASSWORD"
              name: "saas-app-1-config-gqcm"
        - name: "INSTANCE_CONNECTION_NAME"
          valueFrom:
            configMapKeyRef:
              key: "INSTANCE_CONNECTION_NAME"
              name: "saas-app-1-config-gqcm"
        - name: "PUBSUB_TOPIC_SORT"
          valueFrom:
            configMapKeyRef:
              key: "PUBSUB_TOPIC_SORT"
              name: "saas-app-1-config-gqcm"
        - name: "PUBSUB_TOPIC_PALINDROME"
          valueFrom:
            configMapKeyRef:
              key: "PUBSUB_TOPIC_PALINDROME"
              name: "saas-app-1-config-gqcm"
      serviceAccountName: kubernetes-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "saas-app-1-hpa-270t"
  namespace: "sorting-as-a-service"
  labels:
    app: "saas-app-1"
    tier: "backend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "saas-app-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
